spark:
  master: "local[*]"
  app_name: "SparkDataEngineeringApp"
  executor_memory: "2g"
  driver_memory: "2g"
  log_level: "WARN"
  shuffle_partitions: 8
  additional_conf:
    spark.sql.shuffle.partitions: "8"
    spark.sql.execution.arrow.pyspark.enabled: "true"
