spark:
  app_name: "DataEngineering_Project"
  master: "spark://spark-master:7077"
  config:
    spark.driver.memory: "1g"
    spark.executor.memory: "2g"
    spark.executor.cores: "2"
    spark.sql.shuffle.partitions: "4"
    spark.default.parallelism: "4"
    spark.driver.host: "spark-app"
    spark.driver.bindAddress: "0.0.0.0"
    spark.serializer: "org.apache.spark.serializer.JavaSerializer"
    spark.executorEnv.PYSPARK_PYTHON: "/usr/bin/python3"
    spark.executorEnv.PYSPARK_DRIVER_PYTHON: "/usr/bin/python3"
    spark.executorEnv.PYTHONPATH: "/opt/spark/python:/opt/spark/python/lib/py4j-0.10.9.7-src.zip"