spark:
  app_name: "DataEngineering_Project"
  master: "local[*]"
  config:
    spark.driver.memory: "2g"
    spark.executor.memory: "2g"
    spark.sql.shuffle.partitions: "4"
    spark.driver.host: "localhost"